# Generated by Django 4.1.7 on 2023-03-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="actual_return",
            field=models.DateField(blank=True),
        ),
    ]
