# Generated by Django 4.1.7 on 2023-03-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_alter_borrow_actual_return"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="actual_return",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="borrow_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
