# Generated by Django 4.1.7 on 2023-03-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0004_borrow_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrow",
            name="status",
        ),
    ]
